### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by fitbodylife** [nutritionix/nodejs-client-library#1]
i get this error

module.js:340
    throw err;
          ^
Error: Cannot find module './config.testing.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/khoinguyen/Development/appmachine/node_modules/nutritionix/tests/index.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

there is no config.testing.js file

**Comment by mattsilv** [comment]
@fitbodylife Thank you, we are checking into this.

**Comment by sourcec0de** [comment]
@fitbodylife can you provide some context on how you are using the library. It is helpful for us to see the code that threw the error.
